export const HEADLINE_SITES = {
  morningOverview: {
    name: 'Morning Overview',
    country: 'us',
    keywords: [
      'Alien Tech',
      'Ancient Civilizations',
      'Lost Cities',
      'Mars Discoveries',
      'NASA Discoveries',
      'Astronomy Breakthroughs',
      'UFO Reports',
      'Interstellar Objects',
      'SpaceX Updates',
      'Tesla Tech',
      'Military Tech',
      'Energy Breakthroughs',
      'Smartphones',
      'Religious Artifacts',
      'Mysterious Phenomena',
      'Underground Cities',
      'Truck Reliability',
      'SUV Longevity',
      'Artificial Intelligence',
      'Aviation Tech',
    ] as const,
    rssFeeds: [
      'https://www.slashgear.com/feed/',
      'https://modernengineeringmarvels.com/feed/',
      'https://techcrunch.com/feed/',
      'https://www.hotcars.com/feed/',
      'https://interestingengineering.com/feed',
      'https://www.zmescience.com/feed/',
      'https://dailygalaxy.com/feed/',
    ] as const,
  },
  dailyOverview: {
    name: 'The Daily Overview',
    country: 'us',
    keywords: [
      'Fed Rates',
      'Stimulus Checks',
      'Social Security',
      'Retirement Planning',
      'Economic Collapse',
      'Stock Market',
      'Investments',
      'Net Worth',
      'Wealth Building',
      'Passive Income',
      'Frugal Habits',
      'Budgeting',
      'Cars',
      'Used Cars',
      'Electric Vehicles',
      'Housing Market',
      'Affordable Living',
      'Cheap Land',
      'Generational Trends',
      'Remote Jobs',
    ] as const,
    rssFeeds: [
      'https://feeds.content.dowjones.io/public/rss/mw_topstories',
      'https://feeds.content.dowjones.io/public/rss/RSSPersonalFinance',
      'https://feeds.content.dowjones.io/public/rss/latestnewsrealestate',
      'https://feeds.content.dowjones.io/public/rss/WSJcomUSBusiness',
      'https://feeds.content.dowjones.io/public/rss/socialeconomyfeed',
      'https://feeds.content.dowjones.io/public/rss/mw_topstories',
      'https://api.axios.com/feed/',
      'https://www.fool.com/money/feed',
      'https://247wallst.com/feed/',
      'https://www.gobankingrates.com/feed/',
      'https://www.moneytalksnews.com/feed/',
      'https://investedwallet.com/feed/',
      'https://centsandpurpose.com/feed/',
      'https://www.the-express.com/posts/rss/25/personalfinance.',
    ] as const,
  },
  flexibleFridge: {
    name: 'The Flexible Fridge',
    country: 'us',
  },
  californiaAdventure: {
    name: 'California is for Adventure',
    country: 'us',
  },
  oregonAdventure: {
    name: 'Oregon is for Adventure',
    country: 'us',
    keywords: [
      'Oregon travel itinerary',
      'Oregon weekend getaways',
      'Portland travel tips',
      'Oregon road trip ideas',
      'Oregon coast weekend itinerary',
      'Willamette Valley wine tours',
      'Family adventures in Oregon',
      'Bend Oregon outdoor adventures',
      'Columbia River Gorge hiking guide',
      'Crater Lake travel planning',
      'Oregon hot springs road trip',
      'Central Oregon adventure travel',
      'Eastern Oregon scenic byways',
      'Oregon camping guide',
      'Portland foodie weekend itinerary',
      'Oregon waterfall road trip',
      'Oregon family vacation ideas',
      'Oregon national parks travel tips',
      'Southern Oregon wine country escapes',
      'Oregon hidden gem getaways',
    ] as const,
    rssFeeds: [
      'https://traveloregon.com/feed',
      'https://www.travelportland.com/feed/',
      'https://www.outdoorproject.com/feeds/latest',
      'https://hikeoregon.net/blog-feed.xml',
    ] as const,
  },
  washingtonAdventure: {
    name: 'Washington is for Adventure',
    country: 'us',
  },
} satisfies Record<
  string,
  {
    name: string;
    country: 'us';
    keywords?: readonly string[];
    rssFeeds?: readonly string[];
  }
>;

export type HeadlineSiteKey = keyof typeof HEADLINE_SITES;

